---
title: "git_01"
author: "Damian Earp"
date: "Summer 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
’Twas brillig, and the slithy toves  
      Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
      And the mome raths outgrabe.  
  
“Beware the Jabberwock, my son!  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->
I heard a thousand blended notes,  
While in a grove I sate reclined,  
In that sweet mood when pleasant thoughts  
Bring sad thoughts to the mind.  
To her fair works did Nature link  
The human soul that through me ran;  
And much it grieved my heart to think  
What man has made of man.  
Through primrose tufts, in that green bower,  
The periwinkle trailed its wreaths;  
And ’tis my faith that every flower  
Enjoys the air it breathes.  
The birds around me hopped and played,  
Their thoughts I cannot measure:—  
But the least motion which they made  
It seemed a thrill of pleasure.  
  